#conda env create -f environment.yml
#conda env update -f environment.yml --prune
name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - numpy
  - scikit-learn 
  - scipy
  - statsmodels
  - pip
  - pip:
    - seaborn
    - openpyxl
