#conda env create -f environment.yml
#conda env update -f environment.yml --prune
name: notebook
channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - matplotlib
  - numpy
  - scikit-learn 
  - pip
  - pip: